'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace AmountToWords
	Partial Public Class _Default

		'''<summary>
		'''form1 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		'''<summary>
		'''txtAmount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtAmount As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''btnConvert control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents btnConvert As Global.System.Web.UI.WebControls.Button

		'''<summary>
		'''lblResult control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtPalindrome control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtPalindrome As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''btnCheckPalindrome control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents btnCheckPalindrome As Global.System.Web.UI.WebControls.Button

		'''<summary>
		'''lblPalindromeResult control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblPalindromeResult As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lblPalindromeBadge control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblPalindromeBadge As Global.System.Web.UI.WebControls.Label
	End Class
End Namespace
